import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://yesmy-dev:YesMyDev123$@yesmy-dev.azurewebsites.net/devices/');
  await page.getByRole('button', { name: 'Devices' }).click();
  await page.getByRole('link', { name: 'Explore Devices' }).click();
  await page.getByRole('link', { name: 'Buy Now' }).nth(3).click();
  await page.goto('https://yesshop-dev.azurewebsites.net/samsung-galaxy-z-fold-8-old-315/cart');
  await page.getByRole('button', { name: '16GB+1TB' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page).toHaveURL(/\/verification/, { timeout: 30_000 });
  await expect(page.getByRole('heading', { name: 'Verify Personal Details' })).toBeVisible();
  await page.getByLabel('ID Type *').selectOption('MYKAD');
  await page.getByRole('textbox', { name: 'ID Number' }).click();
  await page.getByRole('textbox', { name: 'ID Number' }).fill('050707080098');
  await page.getByRole('textbox', { name: 'Full Name *' }).click();
  await page.getByRole('textbox', { name: 'Full Name *' }).fill('NUR RABIATUL NABILA BINTI TAJUDIn');
  await page.getByRole('spinbutton', { name: 'Phone Number' }).click();
  await page.getByRole('spinbutton', { name: 'Phone Number' }).fill('0168988898');
  await page.getByRole('spinbutton', { name: 'Phone Number' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email Address *' }).fill('');
  await page.getByRole('textbox', { name: 'Email Address *' }).click();
  await page.getByRole('textbox', { name: 'Email Address *' }).fill('USER@GMAIL.COm');
  await page.getByText('By activating the Yes Service').click();
  await page.getByText('I further give consent to').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page).toHaveURL(/\/accessories/, { timeout: 30_000 });
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('heading', { name: 'Delivery Address' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Address *' }).click();
  await page.getByRole('textbox', { name: 'Address *' }).fill('JALAN PANTAI SENTRAl');
  await page.getByRole('textbox', { name: 'Postal Code *' }).click();
  await page.getByRole('textbox', { name: 'Postal Code *' }).fill('55000');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.goto('https://yesshop-dev.azurewebsites.net/samsung-galaxy-z-fold-8-old-315/delivery-addresses/');
  await page.getByRole('textbox', { name: 'Address *' }).click();
});
// time to create the script using codegen: 1m 30s, but it can be faster if you are familiar with the selectors and the flow of the application.
//execution time : 43s
// scripts passed in a single run, but the test is flaky because the selectors are not stable, and the timing of the application is not consistent. 
//debug the script using playwright test results 
//second iteration : 1m 50s for 2 tests and both failed, the selectors are not stable, and the timing of the application is not consistent.
// I create a new test using playwright codegen, and I will try to use more stable selectors and add some waitForSelector to make the test more reliable.
// time to create the new script is 2m 
// the new scripts is in incoming-scripts/YOS-Codegen_device_v2.spec.ts, and it is more stable and reliable than the previous one. 
// it's marked as a green as it passed in average 25s and the selectors are more stable and reliable than the previous one.
// the selector toHaveURL is used to wait for the page to load before proceeding to the next step, and it is more reliable than using waitForSelector.
// it must be authored by hand and cannot be generated by codegen
