import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('a');
  await page.getByRole('button', { name: 'Devices' }).click();
  await page.getByRole('link', { name: 'Explore Devices' }).click();
  await expect(page.locator('#device-list-section')).toContainText('Galaxy A57 5G');
  await page.locator('div:nth-child(15) > .layer-planDevice > .bottom-section > .panel-btn > .btn').click();
  await page.getByRole('tab', { name: 'Awesome Ice Blue' }).click();
  await page.locator('.layer-action-payment-plan-inner > .image-section').click();
  await page.getByRole('button', { name: '36 Months' }).click();
  await page.getByRole('button', { name: 'Infinite+ Premium RM 118 /mth' }).click();
  await expect(page.getByRole('heading', { name: /InfinitePlus Premium/ })).toBeVisible();
  await page.getByRole('button', { name: 'eSIM' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('heading', { name: 'Verify Personal Details' })).toBeVisible();
  await page.getByLabel('ID Type *').selectOption('PASSPORT');
  await page.getByRole('textbox', { name: 'ID Number' }).click();
  await page.getByRole('textbox', { name: 'ID Number' }).fill('P5833558');
  await page.getByRole('textbox', { name: 'Full Name *' }).click();
  await page.getByRole('textbox', { name: 'Full Name *' }).fill('TESTUSER');
  await page.locator('#gender1').selectOption('1');
  await page.getByRole('textbox', { name: 'Date Of Birth *' }).click();
  await page.getByRole('textbox', { name: 'Date Of Birth *' }).fill('06/02/1983');
  await page.getByRole('spinbutton', { name: 'Phone Number' }).click();
  await page.getByRole('spinbutton', { name: 'Phone Number' }).fill('0149645779');
  await page.getByRole('textbox', { name: 'Email Address *' }).click();
  await page.getByRole('textbox', { name: 'Email Address *' }).fill('OBRMEMAIL@GMAIL.COM');
  await page.getByText('By activating the Yes Service').click();
  await page.getByText('I further give consent to').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'PROCEED' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('textbox', { name: 'Address *' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Address *' }).click();
  await page.getByRole('textbox', { name: 'Address *' }).fill('11,JLN PANTAI SENTRAL 3 PANTAI DALAM');
  await page.getByRole('textbox', { name: 'Unit No.' }).click();
  await page.getByRole('textbox', { name: 'Unit No.' }).fill('19-23');
  await page.getByRole('textbox', { name: 'Postal Code *' }).click();
  await page.getByRole('textbox', { name: 'Postal Code *' }).fill('59200');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page).toHaveURL(/payment/, { timeout: 15000 });
  await expect(page.locator('form')).toContainText('Approximately 5-7 working days, subject to stock availability');
});